import { Component, OnInit } from '@angular/core';
import {HospitalService} from "../../shared/hospital.service";
import { MatTabChangeEvent } from '@angular/material';
import {DomSanitizer} from "@angular/platform-browser";

@Component({
  selector: 'app-cde-variables',
  templateUrl: './cde-variables.component.html',
  styleUrls: ['./cde-variables.component.css']
})

export class CdeVariablesComponent implements OnInit {
data = {
    "code": "root",
    "groups": [
      {
        "code": "genetic",
        "groups": [
          {
            "code": "polymorphism",
            "label": "polymorphism",
            "groups": [
              {
                "code": "apoe4",
                "description": "Apolipoprotein E (APOE) e4 allele: is the strongest risk factor for Late Onset Alzheimer Disease (LOAD). At least one copy of APOE-e4 ",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "ApoE4",
                "methodology": "adni-merge",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs3818361_t",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs3818361_T",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs744373_c",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs744373_C",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs190982_g",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs190982_G",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs1476679_c",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs1476679_C",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs11767557_c",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs11767557_C",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs11136000_t",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs11136000_T",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs610932_a",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs610932_A",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs3851179_a",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs3851179_A",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs17125944_c",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs17125944_C",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs10498633_t",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs10498633_T",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs3764650_g",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs3764650_G",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs3865444_t",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs3865444_T",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              },
              {
                "code": "rs2718058_g",
                "description": "",
                "enumerations": [
                  {
                    "code": 0,
                    "label": 0
                  },
                  {
                    "code": 1,
                    "label": 1
                  },
                  {
                    "code": 2,
                    "label": 2
                  }
                ],
                "label": "rs2718058_G",
                "methodology": "lren-nmm-volumes",
                "sql_type": "int",
                "type": "polynominal"
              }
            ]
          },

        ],
        "label": "Genetic"
      },
      {
        "code": "pet",
        "label": "PET - Positron Emission Tomography",
        "groups": [
          {
            "code": "fdg",
            "description": " Average FDG-PET of angular, temporal, and posterior cingulate. Most important hypometabolic regions that are indicative of pathological metabolic change in MCI and AD.",
            "label": "FDG-PET",
            "methodology": "adni-merge",
            "type": "real"
          },
          {
            "code": "pib",
            "description": "Average PIB SUVR of frontal cortex, anterior cingulate, precuneus cortex, and parietal cortex.",
            "label": "PIB",
            "methodology": "adni-merge",
            "type": "real"
          },
          {
            "code": "av45",
            "description": "AV45 Average AV45 SUVR of frontal, anterior cingulate, precuneus, and parietal cortex relative to the cerebellum",
            "label": "AV45",
            "methodology": "adni-merge",
            "type": "real"
          }
        ]
      }]};
data3 = {
  "parent": "",
  "children": [{
    "parent": "root",
    "children": [{
      "parent": "brain_anatomy",
      "children": [{
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightsmcsupplementarymotorcortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightsmcsupplementarymotorcortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftscasubcallosalarea",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftscasubcallosalarea",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftorifgorbitalpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftorifgorbitalpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftsmcsupplementarymotorcortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftsmcsupplementarymotorcortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftprgprecentralgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftprgprecentralgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftcocentraloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftcocentraloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightscasubcallosalarea",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightscasubcallosalarea",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftopifgopercularpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftopifgopercularpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightopifgopercularpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightopifgopercularpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftmsfgsuperiorfrontalgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmsfgsuperiorfrontalgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftpoparietaloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftpoparietaloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "righttrifgtriangularpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "righttrifgtriangularpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftgregyrusrectus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftgregyrusrectus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftsfgsuperiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftsfgsuperiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftmorgmedialorbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmorgmedialorbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightmsfgsuperiorfrontalgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmsfgsuperiorfrontalgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftaorganteriororbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftaorganteriororbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightpoparietaloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightpoparietaloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightmorgmedialorbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmorgmedialorbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightprgprecentralgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightprgprecentralgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightorifgorbitalpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightorifgorbitalpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftmfgmiddlefrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmfgmiddlefrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftfofrontaloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftfofrontaloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftporgposteriororbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftporgposteriororbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "lefttrifgtriangularpartoftheinferiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "lefttrifgtriangularpartoftheinferiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightgregyrusrectus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightgregyrusrectus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightmfgmiddlefrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmfgmiddlefrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftmprgprecentralgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmprgprecentralgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightmfcmedialfrontalcortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmfcmedialfrontalcortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightsfgsuperiorfrontalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightsfgsuperiorfrontalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightmprgprecentralgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmprgprecentralgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightcocentraloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightcocentraloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftlorglateralorbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftlorglateralorbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightfrpfrontalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightfrpfrontalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftfrpfrontalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftfrpfrontalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightaorganteriororbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightaorganteriororbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "leftmfcmedialfrontalcortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmfcmedialfrontalcortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightlorglateralorbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightlorglateralorbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightfofrontaloperculum",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightfofrontaloperculum",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "frontal",
          "unit": "cm3",
          "code": "rightporgposteriororbitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightporgposteriororbitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "frontal"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "insula",
          "unit": "cm3",
          "code": "rightainsanteriorinsula",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightainsanteriorinsula",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "insula",
          "unit": "cm3",
          "code": "leftpinsposteriorinsula",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftpinsposteriorinsula",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "insula",
          "unit": "cm3",
          "code": "leftainsanteriorinsula",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftainsanteriorinsula",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "insula",
          "unit": "cm3",
          "code": "rightpinsposteriorinsula",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightpinsposteriorinsula",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "insula"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "parent": "cerebral_nuclei",
          "children": [{
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "leftbasalforebrain",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftbasalforebrain",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "leftputamen",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftputamen",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "leftcaudate",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftcaudate",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "rightpallidum",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightpallidum",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "rightputamen",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightputamen",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "rightbasalforebrain",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightbasalforebrain",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "rightcaudate",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightcaudate",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "leftpallidum",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftpallidum",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "leftaccumbensarea",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftaccumbensarea",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "basal_ganglia",
            "unit": "cm3",
            "code": "rightaccumbensarea",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightaccumbensarea",
            "description": "",
            "type": "real",
            "methodology": ""
          }],
          "name": "basal_ganglia"
        }, {
          "parent": "cerebral_nuclei",
          "children": [{
            "canBeNull": "",
            "parent": "amygdala",
            "unit": "cm3",
            "code": "leftamygdala",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "leftamygdala",
            "description": "",
            "type": "real",
            "methodology": ""
          }, {
            "canBeNull": "",
            "parent": "amygdala",
            "unit": "cm3",
            "code": "rightamygdala",
            "comments": "",
            "csvFile": "custom_file",
            "values": "",
            "name": "rightamygdala",
            "description": "",
            "type": "real",
            "methodology": ""
          }],
          "name": "amygdala"
        }],
        "name": "cerebral_nuclei"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightpogpostcentralgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightpogpostcentralgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftpcuprecuneus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftpcuprecuneus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightmpogpostcentralgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmpogpostcentralgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftsmgsupramarginalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftsmgsupramarginalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftsplsuperiorparietallobule",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftsplsuperiorparietallobule",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightsmgsupramarginalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightsmgsupramarginalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightangangulargyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightangangulargyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightsplsuperiorparietallobule",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightsplsuperiorparietallobule",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftangangulargyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftangangulargyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftpogpostcentralgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftpogpostcentralgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "leftmpogpostcentralgyrusmedialsegment",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmpogpostcentralgyrusmedialsegment",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "parietal",
          "unit": "cm3",
          "code": "rightpcuprecuneus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightpcuprecuneus",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "parietal"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "diencephalon",
          "unit": "cm3",
          "code": "leftventraldc",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftventraldc",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "diencephalon",
          "unit": "cm3",
          "code": "rightventraldc",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightventraldc",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "diencephalon"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightfugfusiformgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightfugfusiformgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "lefttmptemporalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "lefttmptemporalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftitginferiortemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftitginferiortemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightptplanumtemporale",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightptplanumtemporale",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightttgtransversetemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightttgtransversetemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightppplanumpolare",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightppplanumpolare",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftptplanumtemporale",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftptplanumtemporale",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftmtgmiddletemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmtgmiddletemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftttgtransversetemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftttgtransversetemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightitginferiortemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightitginferiortemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "righttmptemporalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "righttmptemporalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftppplanumpolare",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftppplanumpolare",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightmtgmiddletemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmtgmiddletemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftfugfusiformgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftfugfusiformgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "leftstgsuperiortemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftstgsuperiortemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "temporal",
          "unit": "cm3",
          "code": "rightstgsuperiortemporalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightstgsuperiortemporalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "temporal"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "cerebellum",
          "unit": "cm3",
          "code": "rightcerebellumexterior",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightcerebellumexterior",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "cerebellum",
          "unit": "cm3",
          "code": "leftcerebellumexterior",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftcerebellumexterior",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "cerebellum",
          "unit": "cm3",
          "code": "cerebellarvermallobulesiv",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "cerebellarvermallobulesiv",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "cerebellum",
          "unit": "cm3",
          "code": "cerebellarvermallobulesviiix",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "cerebellarvermallobulesviiix",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "cerebellum",
          "unit": "cm3",
          "code": "cerebellarvermallobulesvivii",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "cerebellarvermallobulesvivii",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "cerebellum"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightmogmiddleoccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmogmiddleoccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftliglingualgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftliglingualgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightofugoccipitalfusiformgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightofugoccipitalfusiformgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightsogsuperioroccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightsogsuperioroccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftcalccalcarinecortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftcalccalcarinecortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftocpoccipitalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftocpoccipitalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightliglingualgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightliglingualgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightioginferioroccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightioginferioroccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftmogmiddleoccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmogmiddleoccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightcalccalcarinecortex",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightcalccalcarinecortex",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftcuncuneus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftcuncuneus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightocpoccipitalpole",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightocpoccipitalpole",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftsogsuperioroccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftsogsuperioroccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "rightcuncuneus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightcuncuneus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftofugoccipitalfusiformgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftofugoccipitalfusiformgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "occipital",
          "unit": "cm3",
          "code": "leftioginferioroccipitalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftioginferioroccipitalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "occipital"
      }, {
        "parent": "grey_matter_volume",
        "children": [{
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightpcggposteriorcingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightpcggposteriorcingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftmcggmiddlecingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftmcggmiddlecingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftpcggposteriorcingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftpcggposteriorcingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftententorhinalarea",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftententorhinalarea",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightententorhinalarea",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightententorhinalarea",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightphgparahippocampalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightphgparahippocampalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightacgganteriorcingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightacgganteriorcingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftacgganteriorcingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftacgganteriorcingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightmcggmiddlecingulategyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightmcggmiddlecingulategyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "righthippocampus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "righthippocampus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftphgparahippocampalgyrus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftphgparahippocampalgyrus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "leftthalamusproper",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "leftthalamusproper",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "lefthippocampus",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "lefthippocampus",
          "description": "",
          "type": "real",
          "methodology": ""
        }, {
          "canBeNull": "",
          "parent": "limbic",
          "unit": "cm3",
          "code": "rightthalamusproper",
          "comments": "",
          "csvFile": "custom_file",
          "values": "",
          "name": "rightthalamusproper",
          "description": "",
          "type": "real",
          "methodology": ""
        }],
        "name": "limbic"
      }],
      "name": "grey_matter_volume"
    }, {
      "parent": "brain_anatomy",
      "children": [{
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "_4thventricle",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "_4thventricle",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "leftinflatvent",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "leftinflatvent",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "_3rdventricle",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "_3rdventricle",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "leftlateralventricle",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "leftlateralventricle",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "csfglobal",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "csfglobal",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "rightinflatvent",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "rightinflatvent",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_volume",
        "unit": "cm3",
        "code": "rightlateralventricle",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "rightlateralventricle",
        "description": "",
        "type": "real",
        "methodology": ""
      }],
      "name": "csf_volume"
    }, {
      "parent": "brain_anatomy",
      "children": [{
        "canBeNull": "",
        "parent": "white_matter_volume",
        "unit": "cm3",
        "code": "opticchiasm",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "opticchiasm",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "white_matter_volume",
        "unit": "cm3",
        "code": "rightcerebralwhitematter",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "rightcerebralwhitematter",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "white_matter_volume",
        "unit": "cm3",
        "code": "leftcerebralwhitematter",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "leftcerebralwhitematter",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "white_matter_volume",
        "unit": "cm3",
        "code": "leftcerebellumwhitematter",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "leftcerebellumwhitematter",
        "description": "",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "white_matter_volume",
        "unit": "cm3",
        "code": "rightcerebellumwhitematter",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "rightcerebellumwhitematter",
        "description": "",
        "type": "real",
        "methodology": ""
      }],
      "name": "white_matter_volume"
    }],
    "name": "brain_anatomy"
  }, {
    "parent": "root",
    "children": [{
      "parent": "genetic",
      "children": [{
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs190982_g",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs190982_g",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs11136000_t",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs11136000_t",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs3851179_a",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs3851179_a",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "apoe4",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "apoe4",
        "description": "Apolipoprotein E (APOE) e4 allele: is the strongest risk factor for Late Onset Alzheimer Disease (LOAD). At least one copy of APOE-e4 ",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs1476679_c",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs1476679_c",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs10498633_t",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs10498633_t",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs3865444_t",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs3865444_t",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs610932_a",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs610932_a",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs3764650_g",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs3764650_g",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs744373_c",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs744373_c",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs3818361_t",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs3818361_t",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs11767557_c",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs11767557_c",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs17125944_c",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs17125944_c",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "polymorphism",
        "unit": "",
        "code": "rs2718058_g",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0,1,2",
        "name": "rs2718058_g",
        "description": "",
        "type": "polynominal",
        "methodology": ""
      }],
      "name": "polymorphism"
    }],
    "name": "genetic"
  }, {
    "parent": "root",
    "children": [{
      "parent": "proteome",
      "children": [{
        "canBeNull": "",
        "parent": "csf_proteome",
        "unit": "",
        "code": "t_tau",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "t_tau",
        "description": "Tau proteins (or \\u03c4 proteins) are proteins that stabilize microtubules. They are abundant in neurons of the central nervous system and are less common elsewhere, but are also expressed at very low levels in CNS astrocytes and oligodendrocytes. Pathologies and dementias of the nervous system such as Alzheimer''s disease and Parkinson''s disease are associated with tau proteins that have become defective and no longer stabilize microtubules properly.",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_proteome",
        "unit": "",
        "code": "p_tau",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "p_tau",
        "description": "Hyperphosphorylation of the tau protein (tau inclusions, pTau) can result in the self-assembly of tangles of paired helical filaments and straight filaments, which are involved in the pathogenesis of Alzheimer''s disease, frontotemporal dementia, and other tauopathies.",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_proteome",
        "unit": "",
        "code": "ab1_42",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "ab1_42",
        "description": "A\\u03b2 is the main component of amyloid plaques (extracellular deposits found in the brains of patients with Alzheimer''s disease). Similar plaques appear in some variants of Lewy body dementia and in inclusion body myositis (a muscle disease), while A\\u03b2 can also form the aggregates that coat cerebral blood vessels in cerebral amyloid angiopathy. The plaques are composed of a tangle of regularly ordered fibrillar aggregates called amyloid fibers, a protein fold shared by other peptides such as the prions associated with protein misfolding diseases.",
        "type": "real",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "csf_proteome",
        "unit": "",
        "code": "ab1_40",
        "comments": "",
        "csvFile": "custom_file",
        "values": "",
        "name": "ab1_40",
        "description": "A\\u03b2 is the main component of amyloid plaques (extracellular deposits found in the brains of patients with Alzheimer''s disease). Similar plaques appear in some variants of Lewy body dementia and in inclusion body myositis (a muscle disease), while A\\u03b2 can also form the aggregates that coat cerebral blood vessels in cerebral amyloid angiopathy. The plaques are composed of a tangle of regularly ordered fibrillar aggregates called amyloid fibers, a protein fold shared by other peptides such as the prions associated with protein misfolding diseases.",
        "type": "real",
        "methodology": ""
      }],
      "name": "csf_proteome"
    }],
    "name": "proteome"
  }, {
    "parent": "root",
    "children": [{
      "canBeNull": "",
      "parent": "demographics",
      "unit": "",
      "code": "agegroup",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“-50y”,”50-59y”,”60-69y”,”70-79y”,”+80y”",
      "name": "agegroup",
      "description": "",
      "type": "polynominal",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "demographics",
      "unit": "months",
      "code": "subjectage",
      "comments": "",
      "csvFile": "custom_file",
      "values": "0-11",
      "name": "subjectage",
      "description": "Exact age of the subject  for datasets that allow such precision.",
      "type": "real",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "demographics",
      "unit": "",
      "code": "handedness",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“R”,”L”,”A”",
      "name": "handedness",
      "description": "Describes the tendency of the patient to use either the right or the left hand more naturally than the other.",
      "type": "polynominal",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "demographics",
      "unit": "",
      "code": "gender",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“M”,”F”",
      "name": "gender",
      "description": "Gender of the patient - Sex assigned at birth",
      "type": "binominal",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "demographics",
      "unit": "years",
      "code": "subjectageyears",
      "comments": "",
      "csvFile": "custom_file",
      "values": "0-130",
      "name": "subjectageyears",
      "description": "Subject age in years.",
      "type": "integer",
      "methodology": ""
    }],
    "name": "demographics"
  }, {
    "canBeNull": "",
    "parent": "root",
    "unit": "",
    "code": "dataset",
    "comments": "",
    "csvFile": "custom_file",
    "values": "“edsd”,”adni”,”ppmi”",
    "name": "dataset",
    "description": "Variable used to differentiate datasets",
    "type": "polynominal",
    "methodology": ""
  }, {
    "parent": "root",
    "children": [{
      "parent": "neuropsychology",
      "children": [{
        "canBeNull": "",
        "parent": "updrs",
        "unit": "",
        "code": "updrshy",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0-5",
        "name": "updrshy",
        "description": "The Hoehn and Yahr scale (HY) is a widely used clinical rating scale  which defines broad categories of motor function in Parkinson\\u2019s disease (PD). It captures typical patterns of progressive motor impairment.",
        "type": "integer",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "updrs",
        "unit": "",
        "code": "updrstotal",
        "comments": "",
        "csvFile": "custom_file",
        "values": "0-172",
        "name": "updrstotal",
        "description": "The unified Parkinson s disease rating scale (UPDRS) is used to follow the longitudinal course of Parkinson s disease. The UPD rating scale is the most commonly used scale in the clinical study of Parkinson s disease.",
        "type": "integer",
        "methodology": ""
      }],
      "name": "updrs"
    }, {
      "canBeNull": "",
      "parent": "neuropsychology",
      "unit": "",
      "code": "minimentalstate",
      "comments": "",
      "csvFile": "custom_file",
      "values": "0-30",
      "name": "minimentalstate",
      "description": "The Mini Mental State Examination (MMSE) or Folstein test is a 30-point questionnaire that is used extensively in clinical and research settings to measure cognitive impairment. It is commonly used to screen for dementia.",
      "type": "integer",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "neuropsychology",
      "unit": "",
      "code": "montrealcognitiveassessment",
      "comments": "",
      "csvFile": "custom_file",
      "values": "0-30",
      "name": "montrealcognitiveassessment",
      "description": "The Montreal Cognitive Assessment (MoCA) was designed as a rapid screening instrument for mild cognitive dysfunction. It assesses different cognitive domains: attention and concentration  executive functions  memory  language  visuoconstructional skills  conceptual thinking  calculations  and orientation. MoCA Total Scores refer to the final count obtained by patients after the complete test is performed.",
      "type": "integer",
      "methodology": ""
    }],
    "name": "neuropsychology"
  }, {
    "canBeNull": "",
    "parent": "root",
    "unit": "cm3",
    "code": "brainstem",
    "comments": "",
    "csvFile": "custom_file",
    "values": "",
    "name": "brainstem",
    "description": "Brainstem volume",
    "type": "real",
    "methodology": ""
  }, {
    "parent": "root",
    "children": [{
      "canBeNull": "",
      "parent": "pet",
      "unit": "",
      "code": "pib",
      "comments": "",
      "csvFile": "custom_file",
      "values": "",
      "name": "pib",
      "description": "Average PIB SUVR of frontal cortex  anterior cingulate  precuneus cortex  and parietal cortex.",
      "type": "real",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "pet",
      "unit": "",
      "code": "fdg",
      "comments": "",
      "csvFile": "custom_file",
      "values": "",
      "name": "fdg",
      "description": "Average FDG-PET of angular  temporal  and posterior cingulate. Most important hypometabolic regions that are indicative of pathological metabolic change in MCI and AD.",
      "type": "real",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "pet",
      "unit": "",
      "code": "av45",
      "comments": "",
      "csvFile": "custom_file",
      "values": "",
      "name": "av45",
      "description": "AV45 Average AV45 SUVR of frontal  anterior cingulate  precuneus  and parietal cortex\\nrelative to the cerebellum",
      "type": "real",
      "methodology": ""
    }],
    "name": "pet"
  }, {
    "parent": "root",
    "children": [{
      "parent": "diagnosis",
      "children": [{
        "canBeNull": "",
        "parent": "dataset_specific_diagnosis",
        "unit": "",
        "code": "ppmicategory",
        "comments": "",
        "csvFile": "custom_file",
        "values": "“PD”,”HC”,”PRODROMA”,”GENPD”,”REGUN”,”REGPD”,”REGUN”",
        "name": "ppmicategory",
        "description": "Terms aggregating the Parkinson s diseases into classes. For this instance the diagnosis given at enrollment is taken as the clinical diagnosis. Note that the diagnosis in this categories are given only for the PPMI data set.",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "dataset_specific_diagnosis",
        "unit": "",
        "code": "edsdcategory",
        "comments": "",
        "csvFile": "custom_file",
        "values": "“AD”,”MCI”,”CN”",
        "name": "edsdcategory",
        "description": "Terms aggregating illnesses into classes. Note that the diagnosis in this categories are given only for the EDSD data set.",
        "type": "polynominal",
        "methodology": ""
      }, {
        "canBeNull": "",
        "parent": "dataset_specific_diagnosis",
        "unit": "",
        "code": "adnicategory",
        "comments": "",
        "csvFile": "custom_file",
        "values": "“AD”,”MCI”,”CN”",
        "name": "adnicategory",
        "description": "Terms aggregating illnesses into classes. Note that the diagnosis in this categories are given only for the ADNI data set.",
        "type": "polynominal",
        "methodology": ""
      }],
      "name": "dataset_specific_diagnosis"
    }, {
      "canBeNull": "",
      "parent": "diagnosis",
      "unit": "",
      "code": "neurodegenerativescategories",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“PD”,”AD”,”HD”,”ALS”,”BD”,”MCI”,”LBD”,”CJD”,”FTD”,”MD”,”CN”",
      "name": "neurogenerativescategories",
      "description": "There will be two broad categories taken into account. Parkinson s disease without disability or light disability: Without fluctuation of the effect. Dementia in Parkinson s disease",
      "type": "polynominal",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "diagnosis",
      "unit": "",
      "code": "alzheimerbroadcategory",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“PD”,”CN”,”Other”",
      "name": "alzheimerbroadcategory",
      "description": "There will be two broad categories taken into account. Alzheimer s disease (AD) in which the diagnostic is 100% certain and <Other> comprising the rest of Alzheimer s related categories. The <Other> category refers to Alzheime s related diagnosis which origin can be traced to other pathology eg. vascular. In this category MCI diagnosis can also be found. In summary  all Alzheimer s related diagnosis that are not pure.",
      "type": "polynominal",
      "methodology": ""
    }, {
      "canBeNull": "",
      "parent": "diagnosis",
      "unit": "",
      "code": "parkinsonbroadcategory",
      "comments": "",
      "csvFile": "custom_file",
      "values": "“PD”,”CN”,”Other”",
      "name": "parkinsonbroadcategory",
      "description": "There will be two broad categories taken into account. Parkinson s disease without disability or light disability: Without fluctuation of the effect. Dementia in Parkinson s disease",
      "type": "polynominal",
      "methodology": ""
    }],
    "name": "diagnosis"
  }, {
    "parent": "root",
    "name": "brain_anatomygrey_matter_volume"
  }, {
    "canBeNull": "",
    "parent": "root",
    "unit": "cm3",
    "code": "tiv",
    "comments": "",
    "csvFile": "custom_file",
    "values": "",
    "name": "tiv",
    "description": "Total intra-cranial volume",
    "type": "real",
    "methodology": ""
  }],
  "name": "root"
};
  allCdeVersions: Array<any>;
  searchTermVar: String;
  searchTermVer: String;
  hierarchical = false;
  currentCdeVersionId = 1;
  data2:any;
  constructor(private hospitalService: HospitalService,private sanitizer: DomSanitizer) { }

  ngOnInit() {
    this.hospitalService.getAllCdeVersions().subscribe(allVersions => {this.allCdeVersions = allVersions});
  }

  setHierarchical(){
    if(this.hierarchical == false){
      this.hierarchical = true;
    }else{
      this.hierarchical = false;
    }
  }

  onLinkClick( versionId) {
   this.currentCdeVersionId = versionId;
  }

  getJsonStringByVersionId(){
    return this.hospitalService.getJsonStringByVersionId(this.currentCdeVersionId).toString();
  }

   download(blob, filename) {
    if (window.navigator.msSaveOrOpenBlob) // IE10+
      window.navigator.msSaveOrOpenBlob(blob, filename);
    else { // Others
      var a = document.createElement("a"),
        url = URL.createObjectURL(blob);
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      setTimeout(function() {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      }, 0);
    }
  }
  exportJson(): void {
    this.data2=this.getJsonStringByVersionId();
    ///we need a proper request
    const c = JSON.stringify(this.data);
    const file = new Blob([c], {type: 'text/json'});
    this.download(file,"cdes_v1.json");
  }
}
